### ISSUE TITLE
Possibility of scraping Chinese Weblio?

### ISSUE THREAD

**Issue by ghost** [Dendroidal/Jap-jap-definition-scraper-from-weblio--Anki-add-on-#2]
Is it possible to add an option so one could search for Chinese word definitions?
Specifically https://cjjc.weblio.jp/ which is the chinese weblio?

**Comment by Dendroidal** [comment]
What are you trying to get from this, specifically?
Definitions of Chinese words in Japanese?
Writing something that scrapes the definitions from https://cjjc.weblio.jp/ should be relatively easy, but I wouldn't be able to format them nicely as with the Japanese definitions (the formatting part is about half the total code, and it took several iterations to get it to where it is, even if it's still not perfect).

**Comment by ghost** [comment]
Yes! That's right, scraping chinese word definitions in japanese :)
I wouldn't mind the unformatted text.
If you have the time to create it I would appreciate it a lot!

>

**Comment by Dendroidal** [comment]
Hi yaoberh,

It's been awhile, but I've finally taken a stab at implementing some basic chinese weblio functionality (I had to postpone it a bit since I had to learn how to better handle updating the add-on - at some point I had four different versions of the add-on in different places, which made things a bit chaotic).

Anyway, to get chinese definitions, first make sure your add-on is up to date. You then need the following: 
the name of the card type should include the word "chinese" ->
the word whose definition you want goes in the 'Words' field ->
you then run bulk definition generation on that card (I haven't implemented chinese functionality when editing the card) ->
the fetched definition will appear in the "Meaning" field

Try it out, and let me know if you run into major issues (though, again, since I don't know Chinese I won't be able to fine-tune the definitions).

**Comment by ghost** [comment]
Oh wow!!!
Thanks so much! I will test it as soon as I can.
😁

2020年8月10日(月) 19:46 Dendroidal <notifications@github.com>:

**Comment by Dendroidal** [comment]
Hi yaoberh, 

Could you maybe let me know if you had the chance to try the Chinese functionality?
Since the question has been addressed I think it's time to close this issue, but I want to try checking with you first.

**Comment by ghost** [comment]
Hey, sorry I didn't give an update! It works flawlessly. Thanks a lot for
your time and effort implementing it ☺️

Dendroidal <notifications@github.com> 于 2020年8月18日星期二 11:17写道：

**Comment by Dendroidal** [comment]
Good to hear it's working.
This particular functionality itself didn't take too long to implement (maybe 30 min), but I'm a noob at programing, so I first had to learn a good way to manage updating the add-on without breaking what's already there.
